log:
    filename: logs/burn_in_data_server.log
    maxSize: 100 MB
    backupCount: 10
    fromaddr: burninatumd@gmail.com
    toaddrs: syp@umd.edu,yangzs@umd.edu
    credentials: <ask_yipeng_for_passwd>  # Ask Yipeng on slack for the password of this account
    interval: 6 HRS

server:
    host: 0.0.0.0
    port: 45678
    stdevRange: 3
    thermChName:
        - COMBINED_WIRE
    thermAlarmThresh: 50
    heartBeatInterval: 1800  # Send an alarm if the client has been not sending anything for the past 10 min
    checkHeartBeatInterval: 60  # Check heart beat every min
