log:
    filename: logs/burn_in_data_server.log
    maxSize: 20 MB
    backupCount: 50
    fromaddr: burninatumd@gmail.com
    toaddrs: syp@umd.edu,yangzs@umd.edu
    credentials: <ask_yipeng_for_passwd>  # Ask Yipeng on slack for the password of this account
    interval: 6 HRS

server:
    host: 0.0.0.0
    port: 45678
    stdevRange: 3
    thermChName:
        - COMBINED_WIRE
    thermAlarmThresh: 50
    heartBeatInterval: 2 HRS  # Send an alarm if the client has been not sending anything for the past 10 min
    checkHeartBeatInterval: 30 MIN  # Check heart beat every min
    itemLength: 10000
